### ISSUE TITLE
Possible log_t_dur misspecification in Stan model file

### ISSUE THREAD

**Issue by lzachmann** [hammerlab/survivalstan#71]
Hi Jacqueline, just wanted to flag a \*possible\* error at Line 42 in your 'pem_survival_model_unstructured.stan' model:

https://github.com/hammerlab/survivalstan/blob/master/survivalstan/stan/pem_survival_model_unstructured.stan#L42

It's entirely possible I'm wrong, but it may need to be: `log_t_dur = log(t_dur);`. Wasn't recovering the right baseline hazard without it. 

Thanks, and great repo!

**Comment by jburos** [comment]
Yes - thank you for catching this! I will fix it now.
