### ISSUE TITLE
Dataframe Merge error in utils.plot_pp_survival (Test pem_survival_model with simulated data notebook)

### ISSUE THREAD

**Issue by prabhjot12** [hammerlab/survivalstan#76]
In the notebook, when I ran the code : 
survivalstan.utils.plot_pp_survival([testfit], by='sex')
I got the following error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-21194165179c> in <module>()
----> 1 survivalstan.utils.plot_pp_survival([testfit], by='sex')

~/.conda/envs/test-env/lib/python3.5/site-packages/survivalstan/utils.py in plot_pp_survival(models, time_element, event_element, num_ticks, step_size, ticks_at, time_col, event_col, fill, by, alpha, pal, subplot, **kwargs)
    326     pp_surv = prep_pp_survival_data(models, time_element=time_element,
    327                                     event_element=event_element, time_col=time_col,
--> 328                                     event_col=event_col, by=by)
    329     print(pp_surv.head())
    330     if by:

~/.conda/envs/test-env/lib/python3.5/site-packages/survivalstan/utils.py in prep_pp_survival_data(models, time_element, event_element, time_col, event_col, by, **kwargs)
    260                          by=None,
    261                          **kwargs):
--> 262     pp_data = prep_pp_data(models, time_element=time_element, event_element=event_element, time_col=time_col, event_col=event_col, **kwargs)
    263     groups = ['iter', 'model_cohort']
    264     if by:

~/.conda/envs/test-env/lib/python3.5/site-packages/survivalstan/utils.py in prep_pp_data(models, time_element, event_element, event_col, time_col, **kwargs)
    250 def prep_pp_data(models, time_element='y_hat_time', event_element='y_hat_event', event_col='event_status', time_col='event_time', **kwargs):
    251     data = [_prep_pp_data_single_model(model=model, event_element=event_element, time_element=time_element, event_col=event_col, time_col=time_col, **kwargs)
--> 252             for model in models]
    253     data = pd.concat(data)
    254     data.sort_values([time_col, 'iter'], inplace=True)

~/.conda/envs/test-env/lib/python3.5/site-packages/survivalstan/utils.py in <listcomp>(.0)
    250 def prep_pp_data(models, time_element='y_hat_time', event_element='y_hat_event', event_col='event_status', time_col='event_time', **kwargs):
    251     data = [_prep_pp_data_single_model(model=model, event_element=event_element, time_element=time_element, event_col=event_col, time_col=time_col, **kwargs)
--> 252             for model in models]
    253     data = pd.concat(data)
    254     data.sort_values([time_col, 'iter'], inplace=True)

~/.conda/envs/test-env/lib/python3.5/site-packages/survivalstan/utils.py in _prep_pp_data_single_model(model, time_element, event_element, sample_col, time_col, event_col, join_with, sample_id_col)
    244     #pp_data['index'] = pp_data['index'].astype(int)
    245     if join_with:
--> 246             pp_data = pd.merge(pp_data, model[join_with], on=sample_col, suffixes=['','_original'])
    247     return pp_data
    248 

~/.conda/envs/test-env/lib/python3.5/site-packages/pandas/core/reshape/merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
     59                          right_index=right_index, sort=sort, suffixes=suffixes,
     60                          copy=copy, indicator=indicator,
---> 61                          validate=validate)
     62     return op.get_result()
     63 

~/.conda/envs/test-env/lib/python3.5/site-packages/pandas/core/reshape/merge.py in __init__(self, left, right, how, on, left_on, right_on, axis, left_index, right_index, sort, suffixes, copy, indicator, validate)
    553         # validate the merge keys dtypes. We may need to coerce
    554         # to avoid incompat dtypes
--> 555         self._maybe_coerce_merge_keys()
    556 
    557         # If argument passed to validate,

~/.conda/envs/test-env/lib/python3.5/site-packages/pandas/core/reshape/merge.py in _maybe_coerce_merge_keys(self)
    984             elif (not is_numeric_dtype(lk)
    985                     and (is_numeric_dtype(rk) and not is_bool_dtype(rk))):
--> 986                 raise ValueError(msg)
    987             elif is_datetimelike(lk) and not is_datetimelike(rk):
    988                 raise ValueError(msg)

ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat

Resolution: 
I debugged the code and in the utils.py, the below function was producing a dataframe pp_data in which the index column had a type str:
 _prep_pp_data_single_model(model, time_element='y_hat_time', event_element='y_hat_event',
                               sample_col=None, time_col='event_time', event_col='event_status',
                               join_with='df_all', sample_id_col=None):

To solve this I just changed the type to int by using below line and the code ran fine without any errors:
    pp_data = pd.merge(pp_event_time, pp_event_status, on=['iter', sample_col, 'model_cohort'])
    **_pp_data['index'] = pp_data['index'].astype(int)_**
    if join_with:
            pp_data = pd.merge(pp_data, model[join_with], on=sample_col, suffixes=['','_original'])
    return pp_data

**Comment by jburos** [comment]
Thanks @prabhjot12 for reporting this - it's really helpful. I believe this bug was introduced due to changes in the behavior of pd.melt, which was used to prepare the pp_data. 

I have updated this with a slightly more general solution which pull the data type from the `join_with` object. Will be folding this fix into the next release.

**Comment by prabhjot12** [comment]
Happy that I could help!
